# TODO: <ramp-icon> percentage
[module/audio]
type = internal/pulseaudio

use-ui-max = false


#format-volume-prefix = "  "
; format-volume-foreground = ${colors.primary}
format-volume = <ramp-volume> <label-volume>

label-volume = %percentage:3%%
interval = 2
ramp-volume-foreground = ${colors.primary}

label-muted = "    0%"
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = " "
ramp-volume-1 = " "
ramp-volume-2 = " "
