[module/xkeyboard]
type = internal/xkeyboard
;blacklist-0 = num lock

label-layout = 
# label-layout-padding = 2
label-layout-foreground = ${colors.primary}
; label-layout-background = #bc99ed

label-indicator-padding = 0
label-indicator-margin = 0
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

label-indicator-on-capslock = A
label-indicator-on-capslock-foreground = ${colors.foreground}
label-indicator-on-capslock-padding-left = 0
label-indicator-off-capslock = a
label-indicator-off-capslock-foreground = ${colors.disabled}
label-indicator-off-capslock-padding-left = 0
label-indicator-off-capslock-padding-right = 0

label-indicator-on-numlock = #
label-indicator-on-numlock-foreground = ${colors.foreground}
label-indicator-on-numlock-padding-left = 1
label-indicator-off-numlock = #
label-indicator-off-numlock-foreground = ${colors.disabled}
label-indicator-off-numlock-padding-left = 1
# label-indcator-on-scrolllock = 󰛀

[module/keystatus]
type = custom/script
;exec = bash -c "[[ $(fcitx5-remote -n) == 'unikey' ]] && echo 'vi' || echo 'de'"
exec = ~/.config/polybar/script/keyboard.sh
interval = 1
label-foreground = ${colors.primary}
click-left = fcitx5-remote -t
