[module/power]
type = custom/text

format = <label>
format-foreground = ${colors.primary}

label = "󰐥 "
; content-padding-right = 4

; click-left = notify-send left
click-left = /home/$USER/.config/polybar/script/powermenu.sh
