config_version = 8

[bar]
order = [ "waybar-repl" ]

    [bar.waybar-repl]
    end = [ "tray", "network", "bluetooth", "volume", "brightness", "group:g2", "battery", "session" ]
    margin_ends = 0
    padding = 8
    panel_overlap = 0
    radius = 0
    shadow = false
    start = [ "notifications", "workspaces", "group:g1", "taskbar" ]

        [[bar.waybar-repl.capsule_group]]
        enabled = true
        fill = "#30364D"
        id = "g1"
        members = [ "cpu", "ram", "temp" ]
        opacity = 1.0
        padding = 6.0

        [[bar.waybar-repl.capsule_group]]
        enabled = true
        fill = "#30364D"
        id = "g2"
        members = [ "network_tx", "network_rx" ]
        opacity = 1.0
        padding = 6.0

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 20

[brightness]
enable_ddcutil = true
minimum_brightness = 0.0099999997764825821

[control_center]
hidden_tabs = [ "power", "weather" ]

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "power_profile"

[desktop_widgets]
enabled = false

[dock]
position = "top"
reserve_space = false
show_dots = true
smart_auto_hide = true

[location]
address = "Dortmund, Germany"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 881.5
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 881.5
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[notification.filter.abrt_applet]
match = "abrt-applet"
show_toast = false

[notification.filter.kitty]
match = "kitty"
override_duration = 2000

[osd]
background_opacity = 0.99999997764825821

    [osd.kinds]
    media = false

[plugins]
enabled = [ "oldirtty/color_picker" ]

[shell]
lang = "en"
niri_overview_type_to_launch_enabled = true
polkit_agent = true

    [shell.animation]
    speed = 1.5000000223517418

    [shell.launcher]
    provider_prefix = "!"

        [shell.launcher.providers.calculator]
        prefix = ""

        [shell.launcher.providers.session]
        prefix = "ses"

        [shell.launcher.providers.wallpaper]
        prefix = "wp"

    [shell.panel]
    clipboard_placement = "attached"
    shadow = false

    [shell.screenshot]
    confirm_region = true
    directory = "/home/minh/Pictures/Screenshot"
    show_cursor = true

    [shell.session]
    show_shortcuts = false

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Storm"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false

[wallpaper]
directory = "/home/minh/Pictures/Screensaver"
enabled = false

    [wallpaper.default]
    path = "/home/minh/Pictures/Screensaver/shiolie.jpg"

    [wallpaper.last]
    path = "/home/minh/Pictures/Screensaver/shiolie.jpg"

    [wallpaper.monitor.HDMI-A-1]
    fill_color = "secondary"

    [wallpaper.monitor.eDP-1]
    fill_color = "primary"

[widget.audio_visualizer]
bands = 127
width = 400

[widget.battery]
capsule = true
capsule_fill = "#30364D"
hide_when_full = true
hide_when_plugged = true

[widget.bluetooth]
capsule = true
capsule_fill = "#30364D"

[widget.brightness]
capsule = true
capsule_fill = "#30364D"

[widget.clipboard]
enabled = false

[widget.clock]
format = "{:%a %d %b}, {:%H:%M:%S}"

[widget.control-center]
enabled = false

[widget.cpu]
display = "text"

[widget.launcher]
enabled = false

[widget.lock_keys]
enabled = false

[widget.media]
enabled = false

[widget.network]
capsule = true
capsule_fill = "#30364D"
show_label = false
vpn_status = "both"

[widget.network_rx]
display = "text"
glyph = "arrow-big-down-filled"

[widget.network_tx]
display = "text"
glyph = "arrow-big-up-filled"
highlight_color = "on_surface"

[widget.notifications]
capsule = true
capsule_fill = "#30364D"

[widget.privacy]
enabled = false

[widget.ram]
display = "text"

[widget.session]
capsule = true
capsule_fill = "#3B2D3D"
color = "#F7768E"

[widget.taskbar]
enabled = false

[widget.temp]
display = "text"

[widget.tray]
capsule = true
capsule_fill = "#30364D"
capsule_radius = "auto"

[widget.volume]
capsule = true
capsule_fill = "#30364D"

[widget.wallpaper]
enabled = false

[widget.workspaces]
capsule = true
capsule_fill = "#30364D"
empty_color = "surface_variant"
focused_color = "primary"
occupied_color = "secondary"
urgent_color = "error"