#! /bin/sh

# start sxhkd (hotkeys)
pgrep -x sxhkd >/dev/null || sxhkd &

# override super with caps
setxkbmap -option caps:super

# desktop
bspc monitor -d 1 2 3 4 5

# start polybar
~/.config/polybar/launch.sh &

# Set bg image
feh --bg-fill ~/pics/background/HoloMyth.png &

# Start picom
# Kinda cpu taxing
# picom -b &
# Alternative: xcompmgr
xcompmgr -n &

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

kitty &
